//! TLS transport helpers for thoth-mesh, shared by `thoth-mesh-node`
//! (accept and dial) and `thoth-mesh-cli` (dial only) so
//! certificate-loading and `rustls` config construction — the
//! security-sensitive part — lives in exactly one place. See
//! [ADR-0016](https://github.com/brunoarueira/thoth-mesh/blob/main/docs/adr/0016-tls-transport-security.md).
//!
//! Trust model: one self-signed CA per mesh (generated by the
//! operator, not this crate — see `docs/OPERATIONS.md`), every node
//! holds a leaf cert signed by it. The accept side ([`server_config`])
//! requests but does not require a client certificate, since the
//! shared client/peer port (ADR-0009) can't know which this
//! connection will turn out to be until a `Hello` arrives; the dial
//! side ([`client_config`]) always verifies the far end's server cert
//! against the CA, and optionally presents its own identity.

mod stream;

use std::io;
use std::path::Path;
use std::sync::{Arc, Once};

use rustls::server::WebPkiClientVerifier;
use rustls::{ClientConfig, RootCertStore, ServerConfig};
use rustls_pki_types::pem::PemObject;
use rustls_pki_types::{CertificateDer, PrivateKeyDer};

pub use stream::MaybeTlsStream;
pub use tokio_rustls::{TlsAcceptor, TlsConnector};

/// Everything that can go wrong loading certs/keys or building a
/// `rustls` config from them.
#[derive(Debug, thiserror::Error)]
pub enum TlsError {
    #[error("reading {path}: {source}")]
    Io {
        path: String,
        #[source]
        source: io::Error,
    },
    #[error("{path} contains no certificates")]
    NoCertificates { path: String },
    #[error("{path} contains no private key")]
    NoPrivateKey { path: String },
    #[error("building TLS config: {0}")]
    Rustls(#[from] rustls::Error),
}

/// Installs `ring` as the process-wide default crypto provider, the
/// first time this is called. `rustls`' config builders panic if no
/// provider has been installed; every config-building function here
/// calls this first, so callers never need to.
fn ensure_crypto_provider() {
    static INSTALL: Once = Once::new();
    INSTALL.call_once(|| {
        // Only fails if a *different* provider already won the race,
        // which is fine - some provider is installed either way.
        let _ = rustls::crypto::ring::default_provider().install_default();
    });
}

/// Loads a PEM-encoded certificate chain from `path`.
pub fn load_certs(path: &Path) -> Result<Vec<CertificateDer<'static>>, TlsError> {
    let path_str = path.display().to_string();
    let certs = CertificateDer::pem_file_iter(path)
        .map_err(|source| TlsError::Io {
            path: path_str.clone(),
            source: pem_error_to_io(source),
        })?
        .collect::<Result<Vec<_>, _>>()
        .map_err(|source| TlsError::Io {
            path: path_str.clone(),
            source: pem_error_to_io(source),
        })?;
    if certs.is_empty() {
        return Err(TlsError::NoCertificates { path: path_str });
    }
    Ok(certs)
}

/// Loads a single PEM-encoded private key from `path` (PKCS#8, RSA,
/// or SEC1/EC — whichever comes first in the file).
pub fn load_private_key(path: &Path) -> Result<PrivateKeyDer<'static>, TlsError> {
    let path_str = path.display().to_string();
    PrivateKeyDer::from_pem_file(path).map_err(|source| match source {
        rustls_pki_types::pem::Error::NoItemsFound => TlsError::NoPrivateKey { path: path_str },
        source => TlsError::Io {
            path: path_str,
            source: pem_error_to_io(source),
        },
    })
}

fn pem_error_to_io(err: rustls_pki_types::pem::Error) -> io::Error {
    io::Error::new(io::ErrorKind::InvalidData, err.to_string())
}

fn root_store(ca_certs: Vec<CertificateDer<'static>>) -> Result<RootCertStore, TlsError> {
    let mut roots = RootCertStore::empty();
    for cert in ca_certs {
        // A CA cert that doesn't parse as a valid trust anchor is a
        // configuration error worth failing startup over, not
        // skipping silently.
        roots
            .add(cert)
            .map_err(|_| rustls::Error::General("invalid CA certificate".into()))?;
    }
    Ok(roots)
}

/// Builds the accept-side TLS config: presents `(cert, key)` as this
/// node's identity, trusts `ca_certs` as the mesh's root(s) of trust,
/// and accepts a connection whether or not it presents a client
/// certificate — one that does gets its identity verified against
/// `ca_certs`; one that doesn't still connects, exactly as
/// unauthenticated as every connection is today. See ADR-0016.
pub fn server_config(
    cert: Vec<CertificateDer<'static>>,
    key: PrivateKeyDer<'static>,
    ca_certs: Vec<CertificateDer<'static>>,
) -> Result<ServerConfig, TlsError> {
    ensure_crypto_provider();
    let roots = Arc::new(root_store(ca_certs)?);
    let verifier = WebPkiClientVerifier::builder(roots)
        .allow_unauthenticated()
        .build()
        .map_err(|err| rustls::Error::General(err.to_string()))?;
    let config = ServerConfig::builder()
        .with_client_cert_verifier(verifier)
        .with_single_cert(cert, key)?;
    Ok(config)
}

/// Builds the dial-side TLS config: trusts `ca_certs` to verify the
/// far end's server certificate, and, if `identity` is given,
/// presents `(cert, key)` as this connection's own client identity —
/// always given for a node dialing another node (a peer dialing a
/// peer always identifies itself); optional for the CLI, which has
/// nothing to prove an identity for yet (see #62). See ADR-0016.
pub fn client_config(
    ca_certs: Vec<CertificateDer<'static>>,
    identity: Option<(Vec<CertificateDer<'static>>, PrivateKeyDer<'static>)>,
) -> Result<ClientConfig, TlsError> {
    ensure_crypto_provider();
    let roots = root_store(ca_certs)?;
    let builder = ClientConfig::builder().with_root_certificates(roots);
    let config = match identity {
        Some((cert, key)) => builder.with_client_auth_cert(cert, key)?,
        None => builder.with_no_client_auth(),
    };
    Ok(config)
}
